// Generated by CoffeeScript 1.6.3
var Index;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

module.exports = new (Index = (function() {
  function Index() {}

  Index.prototype.polvo = true;

  Index.prototype.type = 'template';

  Index.prototype.name = 'html';

  Index.prototype.output = 'js';

  Index.prototype.ext = /\.html?$/m;

  Index.prototype.exts = ['.html', '.html'];

  Index.prototype.compile = function(filepath, source, debug, error, done) {
    var compiled;
    source = source.replace(/\n/g, '\\\n').replace('\'', '\\\'');
    compiled = "module.exports = function() { return '" + source + "'; };";
    return done(compiled, null);
  };

  return Index;

})());
