// Generated by CoffeeScript 1.6.3
var Index;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

module.exports = new (Index = (function() {
  function Index() {}

  Index.prototype.polvo = true;

  Index.prototype.type = 'js';

  Index.prototype.name = 'html';

  Index.prototype.ext = /\.html?$/m;

  Index.prototype.exts = ['.html', '.html'];

  Index.prototype.compile = function(filepath, source, debug, done) {
    var compiled;
    compiled = "module.exports = function() { return '" + source + "'; };";
    compiled = compiled.replace(/\n/g, "\\\n");
    console.log(compiled);
    return done(compiled, null);
  };

  return Index;

})());
